name: Rust Binary Build

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Build Dir
      run: mkdir build-dir
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --target-dir ./build-dir
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ./build-dir/release/e-cli
        name: linux_release_x64
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Create Build Dir
      run: mkdir build-dir
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --target-dir ./build-dir
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ./build-dir/release/e-cli.exe
        name: windows_release_x64
  publish-release:
    needs: [linux-build, windows-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Download Artifacts
        run: ls -R
      - name: Create new Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            linux_release_x64 
            windows_release_x64 