name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - name: Create Build Dir
      run: mkdir build-dir
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --target-dir ./build-dir
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ./build-dir/release/e-tools
        name: linux_release_x64
  windows-build:
    runs-on: windows-latest
    steps:
    - name: Create Build Dir
      run: mkdir build-dir
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r --target-dir ./build-dir
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4.3.3
      with:
        path: ./build-dir/release/e-tools.exe
        name: windows_release_x64
